<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_Calendar</name>
   <tag></tag>
   <elementGuidId>d0e05d07-b249-420f-9f53-209e9000be3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//i[contains(text(),'event')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//i[contains(text(),'event')]</value>
      <webElementGuid>1dfd1484-b283-4a50-a407-d7559930b947</webElementGuid>
   </webElementProperties>
</WebElementEntity>
