<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateContract</name>
   <tag></tag>
   <elementGuidId>bf787487-4b5a-478b-834b-481f618a2b8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@automation-id = 'contractDuedate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>070d3d35-534a-4769-ad03-9ac38769ad87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>automation-id</name>
      <type>Main</type>
      <value>contractDuedate</value>
      <webElementGuid>15346964-d66a-496c-9bdb-65b1d8854432</webElementGuid>
   </webElementProperties>
</WebElementEntity>
