<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_UserID</name>
   <tag></tag>
   <elementGuidId>c99c54e0-fed9-4744-8323-39524702c748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[(contains(text(), '0032') or contains(., '0032'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>425d480a-c8e0-4fa7-bfb0-363f87451304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(text(),'0278')]</value>
      <webElementGuid>ba82a692-34f7-4cb0-8357-f027bdcf0757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0032</value>
      <webElementGuid>984809db-5849-4d56-896c-c5328bde0909</webElementGuid>
   </webElementProperties>
</WebElementEntity>
