<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Attachments_CheckAll</name>
   <tag></tag>
   <elementGuidId>564b4e62-b707-45a6-afde-5a9dfc397bd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attachmentsCheckAll']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attachmentsCheckAll</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39b4992c-0de6-41bc-bfa2-fcaaf1a04203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f3637d90-d1f4-4227-8ca3-b4bd12c15880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attachmentsCheckAll</value>
      <webElementGuid>93ad9b4e-8d9b-47ec-8895-7b5451e8b418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkboxAtch</value>
      <webElementGuid>5a187a19-5bf4-4e06-b42b-af405f8c170b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attachmentsCheckAll&quot;)</value>
      <webElementGuid>85b9993d-14c2-4f4b-b39f-b2e8305e603a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attachmentsCheckAll']</value>
      <webElementGuid>b1eab89b-deeb-4691-a7f3-96082361348e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblAttachments']/thead/tr/th/input</value>
      <webElementGuid>01822c66-977c-4a10-bf65-811788dcfb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/input</value>
      <webElementGuid>0bdc41e2-1888-4700-b7c8-037237b682b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'attachmentsCheckAll']</value>
      <webElementGuid>cde6ff36-2c6f-4119-9b87-9a04214b1d47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
