<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Message</name>
   <tag></tag>
   <elementGuidId>ef0c9104-0d8a-49ea-8dca-48060b2b9294</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='message success fadable']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b449c485-c16e-4709-802e-b132de4a8f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fadable</value>
      <webElementGuid>6104b3e9-4965-4278-98be-3bd0e2ca79a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='message success fadable']</value>
      <webElementGuid>1c2677c8-6871-4431-ad3b-95b6809ea81b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
