<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2.PNG</name>
   <tag></tag>
   <elementGuidId>c4a5b6e1-a6dc-4bed-99cb-aafc5364a5c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblAttachments']/tbody/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.fileLink.tiptip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>15ebd7ff-97e2-42ec-83ba-d361c8588846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>7087eea4-e7ae-4e17-87cd-1a95b7d53bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fileLink tiptip</value>
      <webElementGuid>cd9d76be-8733-41aa-bbba-9e4ba51806a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/symfony/web/index.php/pim/viewAttachment/empNumber/1/attachId/1</value>
      <webElementGuid>cc97d1da-a9d7-4ed3-98d2-1deee906cce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    2.PNG</value>
      <webElementGuid>4d106ab6-2b49-40c6-858d-dcbd39445a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblAttachments&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]/a[@class=&quot;fileLink tiptip&quot;]</value>
      <webElementGuid>a1b1ac58-8d50-406a-93fa-dff7f0c7cf87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblAttachments']/tbody/tr/td[2]/a</value>
      <webElementGuid>577d4d6c-a43e-4ccd-967f-ce1cef673248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2.PNG')]</value>
      <webElementGuid>50b011af-83d3-4dca-bbd0-1484566f9140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Added By'])[1]/following::a[1]</value>
      <webElementGuid>dd21968b-b19f-4691-aade-fd94ffc59872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Added'])[1]/following::a[1]</value>
      <webElementGuid>dad80a8d-b4e7-4b2d-bc78-2857b7eebc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='image/png'])[1]/preceding::a[1]</value>
      <webElementGuid>37af698b-8111-4b1c-9af3-24f9f66f4a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thi'])[1]/preceding::a[1]</value>
      <webElementGuid>57ec429d-74e5-49b4-91a6-fab374ada0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2.PNG']/parent::*</value>
      <webElementGuid>ce795dfe-1042-44f3-a918-1f5ee456a08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/symfony/web/index.php/pim/viewAttachment/empNumber/1/attachId/1')]</value>
      <webElementGuid>6ed09813-9e1b-4c7a-ba0d-eda9d571ac15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>b7e52e8b-de71-4e77-b766-fbeb4efd87f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/symfony/web/index.php/pim/viewAttachment/empNumber/1/attachId/1' and (text() = '
                                    2.PNG' or . = '
                                    2.PNG')]</value>
      <webElementGuid>488204d7-9f90-4ac6-8e90-f8092cedafa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
