<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btnSaveAttachment</name>
   <tag></tag>
   <elementGuidId>6e2951b1-649e-4cf9-96f7-b6ec680754f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSaveAttachment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnSaveAttachment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>574a2d45-15df-4425-a18c-91733005cb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d25bbb5e-4e9e-42cd-9ffa-50c798657b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSaveAttachment</value>
      <webElementGuid>b8829e8e-d8bb-4cc0-a462-ba98ace3c7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveAttachment</value>
      <webElementGuid>1e193063-c0db-4ceb-9044-3d84bed53315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>3a8ba20f-b012-41be-8445-0317c0d4c944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>a2fe8243-05a6-4991-a1b2-81d850e23486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSaveAttachment&quot;)</value>
      <webElementGuid>8f3b1906-528d-425e-ad48-d5091c76e82d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSaveAttachment']</value>
      <webElementGuid>7f655bed-f04a-4446-9bbf-5afb9bd1f6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpAttachment']/fieldset/p/input</value>
      <webElementGuid>a57436e7-a105-4269-b1ab-adecb5eb33d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/form/fieldset/p/input</value>
      <webElementGuid>998b6c15-d6c1-4b9f-ab9f-51e658e38a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnSaveAttachment' and @id = 'btnSaveAttachment']</value>
      <webElementGuid>c2c52e0b-9fc7-4302-81b8-22e7b68ae658</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
