<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_download.png</name>
   <tag></tag>
   <elementGuidId>77fea5fc-a2ac-4493-9bd9-7bd3fa1fee00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblAttachments']/tbody/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.fileLink.tiptip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5da9791c-37d4-4dd8-824c-5f4a775f62a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a7691c60-82e2-42e4-b578-e3e475155c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fileLink tiptip</value>
      <webElementGuid>3f08c07a-9eb4-424f-b445-f717960598cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/symfony/web/index.php/pim/viewAttachment/empNumber/1/attachId/1</value>
      <webElementGuid>ae36844d-d384-4f6e-98f4-670a6caec3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    3333.png</value>
      <webElementGuid>39e1011f-ffa8-4807-869f-36d25d9f5501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblAttachments&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]/a[@class=&quot;fileLink tiptip&quot;]</value>
      <webElementGuid>0f68c3fa-f88a-474b-8da5-db2b4ab194c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblAttachments']/tbody/tr/td[2]/a</value>
      <webElementGuid>b2bd4be9-d80e-4c8c-8da7-de50d94177f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'3333.png')]</value>
      <webElementGuid>d934c803-3a27-4ef0-94cc-2cef147d7825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Added By'])[1]/following::a[1]</value>
      <webElementGuid>ebf75938-7562-4fc7-ab64-37036ededd53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Added'])[1]/following::a[1]</value>
      <webElementGuid>b9ef8b8f-7bc5-43f2-8422-bddc324091e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello'])[1]/preceding::a[1]</value>
      <webElementGuid>ec4df265-4105-412f-8a28-8b0c377842c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='image/png'])[1]/preceding::a[1]</value>
      <webElementGuid>e9ccd03d-0277-4c12-9b47-4ce90745e4b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3333.png']/parent::*</value>
      <webElementGuid>f9281c83-f912-4a0b-b38d-ca1e8345e6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/symfony/web/index.php/pim/viewAttachment/empNumber/1/attachId/1')]</value>
      <webElementGuid>5d0ec5b0-0042-4c36-9d83-a3aff79ae775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>58f7bef4-4470-4f04-9b8c-4107225c839d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/symfony/web/index.php/pim/viewAttachment/empNumber/1/attachId/1' and (text() = '
                                    3333.png' or . = '
                                    3333.png')]</value>
      <webElementGuid>d5f5f5ef-697b-4dcd-8beb-f3ca659f6eca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
