<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>e6af69ef-a5c0-47ff-b0e4-3e75ba85140b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='forgotPasswordLink']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f779fb05-52ce-4203-9509-aefa46c63b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/symfony/web/index.php/auth/requestPasswordResetCode</value>
      <webElementGuid>2deae35d-64f2-45cc-a4d4-892e7bb50d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
      <webElementGuid>b01ed543-8e56-4658-8acf-31ea55aa9a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgotPasswordLink&quot;)/a[1]</value>
      <webElementGuid>39f4dc08-bad9-48d0-b454-6c38115adfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>50eb96ca-df79-42db-9e45-e233a0ccf9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/symfony/web/index.php/auth/requestPasswordResetCode</value>
      <webElementGuid>824a06c4-9ef6-4262-a967-9b886519a5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
      <webElementGuid>a47ea50e-8ddf-4027-a2d2-8a45aaea42ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgotPasswordLink&quot;)/a[1]</value>
      <webElementGuid>410ad299-c9d1-418b-88b5-ee1fc1843109</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forgotPasswordLink']/a</value>
      <webElementGuid>630a533e-259e-44f3-8a4b-03825dae3dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
      <webElementGuid>305e019f-0f88-4494-bdea-e9382d25ac0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>670c519f-e15f-431b-8148-62b194efa890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::a[1]</value>
      <webElementGuid>9549b196-e2c6-407a-bf26-190ff47b146c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
      <webElementGuid>7159f370-2ed2-4833-83a4-28f71bb755b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/symfony/web/index.php/auth/requestPasswordResetCode')]</value>
      <webElementGuid>ffce906d-5d4d-4742-a46c-5acbd82bfa3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>69d30515-8b1a-4fcd-83d7-8d0d85e533fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/symfony/web/index.php/auth/requestPasswordResetCode' and (text() = 'Forgot your password?' or . = 'Forgot your password?')]</value>
      <webElementGuid>b037f198-0dd1-4917-8a8f-f463aa4a1fe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
