<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OrangeHRM, Inc</name>
   <tag></tag>
   <elementGuidId>ef87fda6-5780-4703-bb9a-3fb2996c2460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#footer > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='footer']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98e563d4-26b1-40e4-a876-7de8c0eedb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.orangehrm.com</value>
      <webElementGuid>7dd930a2-d43b-463f-adde-890443340198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>90618175-e960-49e1-89a1-19913acce3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OrangeHRM, Inc</value>
      <webElementGuid>54293915-4830-4e70-973e-8ed479b066ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer&quot;)/div[1]/a[1]</value>
      <webElementGuid>999f9d87-3688-4f4b-983f-78333d12c119</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer']/div/a</value>
      <webElementGuid>4876f400-9a87-4401-83f3-aa2d95016a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'OrangeHRM, Inc')]</value>
      <webElementGuid>b346099b-a350-4426-8ffe-525e216be164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[5]</value>
      <webElementGuid>343666ec-70aa-4702-a0ae-fb6e195f313e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::a[5]</value>
      <webElementGuid>f37c26dd-e0f3-4c85-a9f6-e5e633f17c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OrangeHRM, Inc']/parent::*</value>
      <webElementGuid>d7b8626c-7b33-43c1-88fb-fa5e8e974ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.orangehrm.com']</value>
      <webElementGuid>557ab505-9234-4364-a3fe-39c11ef9e112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>6cf15010-8df1-4aa2-a021-ab7ca91da763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.orangehrm.com' and (text() = 'OrangeHRM, Inc' or . = 'OrangeHRM, Inc')]</value>
      <webElementGuid>4fc02b62-c541-4dcf-94de-5b746f7054c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
