<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>f3d5f938-a782-4c1e-b36e-d285b2aa0066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='chkattdel[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;chkattdel[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04ed2933-123b-46a4-8887-f8e377ee6f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4b24dfab-1036-41e9-816e-bb7cbf8357ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkboxAtch</value>
      <webElementGuid>8df26355-dff1-4e95-a486-7e7e99d5d10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chkattdel[]</value>
      <webElementGuid>ba494fa0-a22a-461d-81a4-60edd41fa284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>b62eef9d-1cf9-491e-8c66-5bc601f712c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblAttachments&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;center&quot;]/input[@class=&quot;checkboxAtch&quot;]</value>
      <webElementGuid>6d1d63d8-6177-491b-813f-607bb61a3631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='chkattdel[]']</value>
      <webElementGuid>6cdbe49d-72c1-4c0b-ac96-6a333a8e415a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblAttachments']/tbody/tr/td/input</value>
      <webElementGuid>ed6c005a-0953-43fb-ba1f-8a2812c4f16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>b3a75787-cac6-4566-9ce6-6ce413b6517b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chkattdel[]']</value>
      <webElementGuid>d9869bc1-47ef-4375-aa6f-364049f9bbf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
