<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Date of Birth</name>
   <tag></tag>
   <elementGuidId>6ab9989a-a64f-4a88-a24d-a8e10592f34e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[3]/li[4]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>67aeb682-8ea8-4457-866a-cebe0d98ac07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>0dd72b67-b052-4693-966f-bb6009570e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/symfony/web/webres_62a99229343a71.79046770/themes/default/images/calendar.png</value>
      <webElementGuid>fc08e0ac-f828-4905-a10b-777d29bcb6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmEmpPersonalDetails&quot;)/fieldset[1]/ol[3]/li[4]/img[@class=&quot;ui-datepicker-trigger&quot;]</value>
      <webElementGuid>a3046e44-0d47-4bb3-a339-dbac1898bc41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[3]/li[4]/img</value>
      <webElementGuid>902c59dd-6270-4721-9a19-76d9314b4275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[3]/li[4]/img</value>
      <webElementGuid>0814d1b4-9baa-4bd1-94b9-408079afd3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/symfony/web/webres_62a99229343a71.79046770/themes/default/images/calendar.png']</value>
      <webElementGuid>d8dbab47-60ec-4e8c-a4c1-5ece7b91d8e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
