<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_License Expiry Date</name>
   <tag></tag>
   <elementGuidId>7942a7ed-ae22-453d-8106-6206edee279a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.ui-datepicker-trigger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[2]/li[4]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>744279e8-027f-443b-996d-9bb867b20512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>24388259-7634-4a63-a108-5a747705f3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/symfony/web/webres_62a99229343a71.79046770/themes/default/images/calendar.png</value>
      <webElementGuid>5c789a4c-eac2-40bd-bbf0-41aebe189689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmEmpPersonalDetails&quot;)/fieldset[1]/ol[2]/li[4]/img[@class=&quot;ui-datepicker-trigger&quot;]</value>
      <webElementGuid>11a23663-9f13-42f7-9c29-603f9e5a25a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[2]/li[4]/img</value>
      <webElementGuid>4b2dbe0c-5651-4be0-abba-2397a78fd0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/img</value>
      <webElementGuid>0fd58ad2-86a2-4e65-b702-377925f04ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/symfony/web/webres_62a99229343a71.79046770/themes/default/images/calendar.png']</value>
      <webElementGuid>8df1a986-84fa-42cc-ab6f-04cc442f8983</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
