<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select File_ufile</name>
   <tag></tag>
   <elementGuidId>562b6f16-d6ea-4f29-a8e8-ba51c5c873dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ufile']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ufile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8d4feb0-c614-478c-a675-03a36e9da1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>1d2c6e49-9e38-4187-bbd0-b67d11dbaa7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ufile</value>
      <webElementGuid>a74fc0ec-4636-4aa6-a0b2-179d387f82ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ufile</value>
      <webElementGuid>4accb70c-6b5f-4015-8362-8380e224384e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ufile&quot;)</value>
      <webElementGuid>b4a224fc-7e08-476f-9363-4c8f43b3dbad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ufile']</value>
      <webElementGuid>416f4d87-1b1c-425e-b04b-3877a1408891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpAttachment']/fieldset/ol/li[2]/input[2]</value>
      <webElementGuid>4e5dea59-d885-4756-9cda-94351fb120ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input[2]</value>
      <webElementGuid>b64430d5-466a-44c6-9799-f10418c6cef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'ufile' and @id = 'ufile']</value>
      <webElementGuid>239f8e39-5ca2-4923-92ce-658a395fe44d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
