<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_License Expiry Date_personaltxtLicExpDate</name>
   <tag></tag>
   <elementGuidId>2e4e6fab-5cab-455a-9c62-b30da00b6e55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_txtLicExpDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#personal_txtLicExpDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b60049b3-9c98-47b8-9d6c-98e66d2c6af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_txtLicExpDate</value>
      <webElementGuid>5f8895d8-f007-429c-b985-ad834bfbea28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b429bfd4-1998-446e-ba94-24359030c08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[txtLicExpDate]</value>
      <webElementGuid>5cfc485e-304a-4bb5-87e7-84c9920a45db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar editable calendar hasDatepicker</value>
      <webElementGuid>858e8b3a-f768-4c9a-88b0-ec4fd4891845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_txtLicExpDate&quot;)</value>
      <webElementGuid>af62a97b-a01f-4278-9bb7-91628f479466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81f44150-3740-4f81-b16d-6bc81b1f3d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_txtLicExpDate</value>
      <webElementGuid>4555926a-13e9-49b9-b4b2-f57211ab3d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2030-01-20</value>
      <webElementGuid>cf99b3ff-af82-4fc4-8435-7649eca5a65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7a07542-d1e4-47d9-8fef-3be46720a0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[txtLicExpDate]</value>
      <webElementGuid>5b5db1cc-f4a1-4200-93cc-6aeb35377c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar editable calendar hasDatepicker</value>
      <webElementGuid>498cb68c-9226-4feb-9d6b-5bca821a7b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_txtLicExpDate&quot;)</value>
      <webElementGuid>1d1555d7-ce64-4d72-88a7-3f582c2402b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b16db5d-0491-4f5f-9bc4-ce61172fae96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_txtLicExpDate</value>
      <webElementGuid>a8e240e8-de58-4644-adc5-79eb251140b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2030-01-20</value>
      <webElementGuid>adc56e1e-5bb3-485e-97e5-3c4754a6df29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c756523-b4c6-4188-8155-4e308c42b593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[txtLicExpDate]</value>
      <webElementGuid>e4c04a70-42a4-4436-92e8-60883b2bd413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar editable calendar hasDatepicker</value>
      <webElementGuid>7457e97b-ceef-4795-9249-c452b09b789b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_txtLicExpDate&quot;)</value>
      <webElementGuid>fb2dc57b-2340-4143-9650-c28ea893ead8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_txtLicExpDate']</value>
      <webElementGuid>7f95f6ae-fd88-4c0d-8562-78571411983d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[2]/li[4]/input</value>
      <webElementGuid>dacd438e-95ff-4ecb-84a1-b7795bd67494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/input</value>
      <webElementGuid>68f28271-bc87-450c-85d3-aeb095c431bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'personal_txtLicExpDate' and @type = 'text' and @name = 'personal[txtLicExpDate]']</value>
      <webElementGuid>f50480a6-54b2-4aa8-b379-3e4c08c4106d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
