<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Driver, , s License Number)_personaltxtLicenNo</name>
   <tag></tag>
   <elementGuidId>fa1b3390-c958-40b9-bbd3-e62c7719f093</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal_txtLicenNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#personal_txtLicenNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ab6abcd-267e-4ce1-bc83-0c9921771274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d330b0d-bd7b-4e6f-8ae1-17d946679364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[txtLicenNo]</value>
      <webElementGuid>9e1f3fbe-5bf7-418e-a5e3-bccb56e40146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>9cdc5a18-78bb-4887-9fa2-c0e79e448ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>a92621c5-1300-4baa-a4a5-7da61ce7638a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_txtLicenNo</value>
      <webElementGuid>30ea4830-a05d-415b-9ec4-4bbcd54c3416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>70e39417-c57c-4b31-a838-2af9ce60d571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_txtLicenNo&quot;)</value>
      <webElementGuid>4f6ba62e-5331-42c2-885f-44b01d506cf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal_txtLicenNo']</value>
      <webElementGuid>3008528e-d5d3-4d0a-9ad2-cc4a6dff217b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpPersonalDetails']/fieldset/ol[2]/li[3]/input</value>
      <webElementGuid>3183cbd0-0dcc-4717-a524-dcc0acfd1819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[2]/li[3]/input</value>
      <webElementGuid>22aa4a7f-6ffc-4015-abbd-5eaf5f374b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'personal[txtLicenNo]' and @id = 'personal_txtLicenNo']</value>
      <webElementGuid>1c0d8319-c839-4817-8518-4bc03d703ebf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
