<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_empPic</name>
   <tag></tag>
   <elementGuidId>ca80c344-240d-4de5-8f0e-935ee6e12a8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empPic</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@alt = 'Employee Photo' and @src = '/symfony/web/index.php/pim/viewPhoto/empNumber/5' and @id = 'empPic']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='empPic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fd827d40-31a5-464f-a2c6-0eaaa83378e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Employee Photo</value>
      <webElementGuid>99b37795-7429-47d2-b4dc-4365ca1b8bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/symfony/web/index.php/pim/viewPhoto/empNumber/5</value>
      <webElementGuid>14ad38f0-8bb5-4310-9e46-6661bbc3792d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>09d95645-41d9-4e60-920e-6a42b7fde992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empPic</value>
      <webElementGuid>587d3063-6903-4d93-b38c-b56a49a2fc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>79000876-d61e-4bfe-b3ca-ad610c7267b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>49a9017a-8ee9-4796-9c22-50cee59ea716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empPic&quot;)</value>
      <webElementGuid>228c8d5f-46b4-481d-a3ee-06506c4a98dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='empPic']</value>
      <webElementGuid>04b11afd-f894-4a77-8736-a5c2d5707947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile-pic']/div/a/img</value>
      <webElementGuid>4013a5d3-e371-4d40-9e18-2a5521bf3945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Employee Photo']</value>
      <webElementGuid>76967277-5650-487f-8995-1b9932dc8aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/img</value>
      <webElementGuid>efb967fe-b94c-4b73-91cd-5a3a2feca59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Employee Photo' and @src = '/symfony/web/index.php/pim/viewPhoto/empNumber/5' and @id = 'empPic']</value>
      <webElementGuid>b1064e4b-ce82-45b0-8346-524116a17092</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
