<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_photofile</name>
   <tag></tag>
   <elementGuidId>5b390e80-2620-4bd9-86a0-ba392fed784c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#photofile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='photofile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0df923ef-aef7-41a0-b749-8302edd6184e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>7e82e410-e309-4a27-869f-061c9abc0c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>photofile</value>
      <webElementGuid>8f9f7b52-04cf-480d-b4ae-0c2b6f955876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>photofile</value>
      <webElementGuid>fdd36423-feb9-40d4-928c-0b229f327bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;photofile&quot;)</value>
      <webElementGuid>0db6a4de-09fb-4748-9943-6ead6f1fb028</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='photofile']</value>
      <webElementGuid>d7aaa091-85bd-48ea-bf45-bcc0c26bfa30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmPhoto']/fieldset/ol/li/input</value>
      <webElementGuid>d561b888-1d8f-4ca1-acbf-30408ab367ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>e95d2418-6513-448e-bd41-b6e4fac0d835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'photofile' and @id = 'photofile']</value>
      <webElementGuid>53ba43c5-dd90-4a48-80dd-bab6cc640853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
