<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Select a Photograph</name>
   <tag></tag>
   <elementGuidId>57889dd7-5915-4097-aaaf-929da00c8d12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmPhoto']/fieldset/ol/li/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>50b9df45-e35f-46af-b40a-edb10b3b06ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>photofile</value>
      <webElementGuid>4628a1c5-caf8-407d-9c96-3b3df5c02f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a Photograph</value>
      <webElementGuid>a992ab03-53bd-47a2-926b-b4ae55995c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPhoto&quot;)/fieldset[1]/ol[1]/li[1]/label[1]</value>
      <webElementGuid>93f20385-e5c8-4f66-ab57-6014650d8c08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmPhoto']/fieldset/ol/li/label</value>
      <webElementGuid>bc2b9210-55db-4da2-8ead-74f00d6e2551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photograph'])[1]/following::label[1]</value>
      <webElementGuid>9cbd8da9-efe5-4aef-a753-aab5d516c615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memberships'])[1]/following::label[1]</value>
      <webElementGuid>84f5aeab-e7a4-49d0-b922-48fe8e0fb82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::label[2]</value>
      <webElementGuid>e50588ce-b430-4968-878e-91ad383726eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrangeHRM - Confirmation Required'])[1]/preceding::label[2]</value>
      <webElementGuid>070358fd-d68f-4a81-b5a2-c3aca696ae38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select a Photograph']/parent::*</value>
      <webElementGuid>4a02eca8-a5e0-4c0f-a3d0-5938f50fb82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>c861fe7b-15ae-45cd-a7a8-f653eaa017e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Select a Photograph' or . = 'Select a Photograph')]</value>
      <webElementGuid>f9c5a915-430e-480d-a84f-98be3202ad4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
